# Site settings
title: Jordan Moore | Responsive Web Design, UX Design, Belfast Northern Ireland
email: madebyjordan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Freelance responsive web designer in Belfast, Northern Ireland, specialising in user experience and accessible design
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jordanm.co.uk" # the base hostname & protocol for your site
# url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
# url: "http://localhost:3000/" # the base hostname & protocol for your site
twitter_username: jordanmoore
github_username:  jordanmoore
paginate: 10
exclude: [node_modules]
paginate_path: "/blog/page:num/"
gems:
  - jekyll-redirect-from
  - jekyll-paginate

# Build settings
markdown: kramdown
sass:
  style: compressed
