# Site settings
title: Jordan Moore | Responsive Web Design, UX Designer, Northern Ireland
email: madebyjordan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Freelance responsive web designer in Belfast, Northern Ireland, specialising in user experience and accessible design
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: "/blog/:title.html"
url: "http://jordanm.co.uk/" # the base hostname & protocol for your site
twitter_username: jordanmoore
github_username:  jordanmoore
paginate: 10
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
sass:
  style: compressed